const AppConst = {
  LoginHeading: "Sign in",
  LoginSubHeading: "Sign In if you have an account here",
  EmailLabel: "Your Email",
  PasswordLabel: "Password",
  EmailPlaceHolder: "Enter Your Email",
  PasswordPlaceHolder: "Enter Your Password",
  ForgotPasswordText: "Forgot Password ?",
  LoginButtonText: "Sign In",
  RegisterText1: "Not a member ?",
  RegisterText2: "Signup",
  RegisterHeading: "Doctor Registration",
  TitleLabel: "Title",
  TitlePlaceHolder: "Select Title",
  FirstNameLabel: "First Name",
  FirstNamePlaceHolder: "Enter First Name",
  LastNameLabel: "Last Name",
  LastNamePlaceHolder: "Enter Last Name",
  MobileNumberLabel: "Mobile Number",
  MobileNumberPlaceHolder: "Enter Mobile Number",
  GMCLabel: "GMC or Prescriber Number",
  GMCLabelPlaceHolder: "Enter GMC or Prescriber Number",
  SpecialityLabel: "Speciality",
  SpecialityPlaceHolder: "Enter Speciality",
  ClinicNameLabel: "Clinic Name",
  ClinicNamePlaceHolder: "Enter Clinic Name - Prescription Address",
  StreetLabel: "Street",
  StreetPlaceHolder: "Enter Street",
  CityLabel: "City",
  CityPlaceHolder: "Enter City",
  PostalCodeLabel: "Postal Code",
  PostalCodePlaceHolder: "Enter Postal Code",
  CountryLabel: "Country",
  CountryPlaceholder: "Select Country",
  ConsentText: "I Consent",
  ConsentSubText:
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus illum omnis architecto eum magni minima quam hic illo? Aliquam, atque!",
  RegisterButtonText: "Submit",
  DashboardHeading: "Dashboard",
  DashboardSearchPatient: "Search Patient or Add New Patient",
  DashboardCardText1: "Sent Scripts",
  DashboardCardSubText1: "All Scripts",
  DashboardCardSubText2: "Sent Scripts",
  DashboardCardText2: "Mailed Scripts",
  DashboardCardText3: "Dispensed Scripts",
  DashboardCardText4: `All Scripts`,
  DashboardCardText5: "Patients Visit",
  DashboardCardText6: "Cancelled Scripts",
  DashboardTableName: "Prescriptions",
  SearchPatientHeading: "Search Patient",
  PatientProfile: "Patient Profile",
  NewPrescription: "New Prescription",
  Save: "Save",
  Next: "Next",
  AddItem: "Add Item",
  SearchPharmacy: "Search Pharmacy",
  Pharmacies: "Pharmacies",
  Search: "Search",
  RegisteredPharmacies: "Registered Pharmacies",
  UnRegisteredPharmacies: "UnRegistered Pharmacies",
  ConfirmToSend: "Confirm To Send",
  PrintDocument: "Print Document",
  SendScript: "Send Script",
  Email: "Email",
  Fax: "Fax",
  FaxPlaceHolder: "Enter Fax no",
  ClinicHeading: "Clinic Registration",
  ContactFirstNamePlaceHolder: "Enter Contact first name",
  ContactLastNamePlaceHolder: "Enter Contact last name",
  ContactFirstNameLabel: "Contact first name",
  ContactLastNameLabel: "Contact last name",
  ConfirmPassword: "Confirm password",
  YourClinicians: "Your Clinicians",
  AddClinicians: "Add Clinicians",
  ShareLink: "Share clinician registration link",
  RegsiterClinic: "Register clinician now",
  Address1Placeholder: "Enter Address 1",
  Address1label: "Address Line 1",
  Address2Placeholder: "Enter Address 2",
  Address2label: "Address Line 2",
  TownCityPlaceholder: "Enter Town/City",
  TownCityLabel: "Town/City",
  ClinicTelephoneNumberPlaceholder: "Enter Clinic Telephone Number",
  ClinicTelephoneNumberLabel: "Clinic Telephone Number",
  ClinicEmailAddressPlaceholder: "Enter Clinic Email Address",
  ClinicEmailAddressLabel: "Clinic Email Address",
  ChooseFile: "Choose File",
  ClinicWebsitePlaceHolder: "Enter Clinic Website",
  ClinicWebsiteLabel: "Clinic Website",
  CqcRegisterNumberPlaceholder: "Enter CQC Register Number",
  CqcRegisterNumberLabel: "CQC Register Number",
  RegisteredManagerNamePlaceHolder: "Enter Registered Manager Name",
  RegisteredManagerNameLabel: "Registered Manager Name",
  NominatedIndividualNamePlaceHolder: "Enter Nominated Individual Name",
  NominatedIndividualNameLabel: "Nominated Individual Name",
  NominatedIndividualEmailPlaceHolder: "Enter Nominated Individual Email",
  NominatedIndividualEmailLabel: "Nominated Individual Email",
  AreaType: "Select Area of type/speciality",
  Submit: "Submit",
  PharmacyRegistration: "Pharmacy Registration",
  PharmacyNamePlaceholder: "Enter Pharmacy Name",
  PharmacyNameLabel: "Pharmacy Name",
  GphcPlaceholder: "Enter GPHC Owner no",
  GphcLabel: "GPHC Owner no",
  SuperIntendentPlaceholder: "Enter Superintendent Name",
  SuperIntendentLabel: "Superintendent Name",
  SuperIntendentGPHCPlaceholderNo: "Enter Superintendent GPHC No",
  SuperIntendentGPHCLabel: "Superintendent GPHC No",
  AddressPlaceholder: "Enter Address",
  Addresslabel: "Address",
  AddPharmacist: "Add Pharmacist",
  SearchPharmacist : 'Search Pharmacist'
};

export const MenuConstants = {
  Dashboard: "Dashboard",
  Patient: "Patient",
  Medicine: "Medicine",
  Pharmacist: "Pharmacist",
};

export default AppConst;
