const AppConst = {
    LoginHeading : 'Sign in',
    LoginSubHeading : 'Sign In if you have an account here',
    EmailLabel : 'Your Email',
    PasswordLabel : 'Password',
    EmailPlaceHolder : 'Enter Your Email',
    PasswordPlaceHolder : "Enter Your Password",
    ForgotPasswordText : "Forgot Password ?",
    LoginButtonText : 'Sign In',
    RegisterText1 : "Not a member ?",
    RegisterText2 : "Signup",
    RegisterHeading : "Doctor Registration",
    TitleLabel : 'Title',
    TitlePlaceHolder : 'Select Title',
    FirstNameLabel : 'First Name',
    FirstNamePlaceHolder : 'Enter First Name',
    LastNameLabel : 'Last Name',
    LastNamePlaceHolder : 'Enter Last Name',
    MobileNumberLabel : 'Mobile Number',
    MobileNumberPlaceHolder : 'Enter Mobile Number',
    GMCLabel : "GMC or Prescriber Number",
    GMCLabelPlaceHolder : "Enter GMC or Prescriber Number",
    SpecialityLabel : "Speciality",
    SpecialityPlaceHolder : "Enter Speciality",
    ClinicNameLabel : "Clinic Name",
    ClinicNamePlaceHolder : "Enter Clinic Name - Prescription Address",
    StreetLabel : "Street",
    StreetPlaceHolder : "Enter Street",
    CityLabel : "City",
    CityPlaceHolder : "Enter City",
    PostalCodeLabel : "Postal Code",
    PostalCodePlaceHolder : "Enter Postal Code",
    CountryLabel : "Country",
    CountryPlaceholder : "Select Country",
    ConsentText : "I Consent",
    ConsentSubText : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus illum omnis architecto eum magni minima quam hic illo? Aliquam, atque!",
    RegisterButtonText : "Submit",
    DashboardHeading : "Dashboard",
    DashboardSearchPatient : 'Search Patient or Add New Patient',
    DashboardCardText1 : 'Sent Scripts',
    DashboardCardSubText1 : 'All Scripts',
    DashboardCardSubText2 : 'Sent Scripts',
    DashboardCardText2 : 'Mailed Scripts',
    DashboardCardText3 : 'Dispensed Scripts',
    DashboardCardText4 : `All Scripts`, 
    DashboardCardText5 : 'Patients Visit',
    DashboardCardText6 : 'Cancelled Scripts',
    DashboardTableName : 'Prescriptions',
    SearchPatientHeading : 'Search Patient',
    PatientProfile : 'Patient Profile',
    NewPrescription : 'New Prescription',
    Save : "Save",
    Next : 'Next',
    AddItem : 'Add Item',
    SearchPharmacy : 'Search Pharmacy',
    Pharmacies : 'Pharmacies',
    Search : 'Search',
    RegisteredPharmacies : 'Registered Pharmacies',
    UnRegisteredPharmacies : 'UnRegistered Pharmacies',
    ConfirmToSend : 'Confirm To Send',
    PrintDocument : 'Print Document',
    SendScript : 'Send Script',
    Email : 'Email', 
    Fax : 'Fax',
    ClinicHeading : 'Clinic Registration',
    ContactFirstNamePlaceHolder : 'Enter Contact first name',
    ContactLastNamePlaceHolder : 'Enter Contact last name',
    ContactFirstNameLabel : 'Contact first name',
    ContactLastNameLabel : 'Contact last name',
    ConfirmPassword : 'Confirm password',
    YourClinicians : 'Your Clinicians',
    AddClinicians : 'Add Clinicians'

}

export const MenuConstants = {
    Dashboard : "Dashboard",
    Patient : "Patient",
    Medicine : "Medicine",
    Pharmacist : "Pharmacist"
}

export default AppConst;